[package]
name = "samoid"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
tempfile = "3.13"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

