[package]
name = "samoyed"
version = "0.1.6"
edition = "2024"
description = "A modern native Git hooks manager implemented in Rust"
license = "MIT"

[[bin]]
name = "samoyed"
path = "src/main.rs"

[[bin]]
name = "samoyed-hook"
path = "src/hook_runner.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml = "0.9"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"


[dev-dependencies]
tempfile = "3.13"
criterion = "0.7"

[[bench]]
name = "benchmark"
harness = false
path = "tests/benches/benchmark.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
