[package]
name = "samoyed"
version = "0.1.9"
authors = ["Behrang Saeedzadeh <hello@behrang.org>"]
edition = "2024"
rust-version = "1.88.0"
readme = "README.md"
homepage = "https://github.com/nutthead/samoyed"
repository = "https://github.com/nutthead/samoyed"
license = "MIT"
description = "A modern native Git hooks manager implemented in Rust"
keywords = ["git", "git-hooks", "git-hooks-manager", "husky"]
exclude = [".samoyed/", "samoyed.toml", "docs/", ".claude/", "CLAUDE.md"]

[[bin]]
name = "samoyed"
path = "src/main.rs"

[[bin]]
name = "samoyed-hook"
path = "src/hook_runner.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
toml = "0.9"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"


[dev-dependencies]
tempfile = "3.13"
criterion = "0.7"

[[bench]]
name = "benchmark"
harness = false
path = "tests/benchmark_tests/benchmark.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
