[hooks]
pre-commit = "cargo fmt --check && cargo clippy --all-targets --all-features -- -D warnings && cargo test --message-format short"
pre-push = "cargo clippy --all-targets --all-features -- -D warnings && cargo test --message-format short --release"
