[hooks]
pre-commit = "cargo fmt --message-format short --all --check && cargo clippy --all-targets --all-features -- -D warnings"
pre-push = "cargo clippy --all-targets --all-features -- -D warnings && cargo test --message-format short --release"
