# ============================================================================
# Release PR Workflow
# ============================================================================
# Automated release management with release-plz
# - Monitors master for versionable changes
# - Opens or updates release pull requests
# - Uses rust-cache for faster runs
# - Respects [skip ci] commit hints

name: Release PR

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'assets/**'
      - 'tests/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/release-pr.yml'
      - 'clippy.toml'
      - 'install.sh'
      - 'uninstall.sh'

permissions:
  contents: write
  pull-requests: write

env:
  RUST_VERSION: "1.90.0"
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    # Skip if commit message contains [skip ci] to prevent unnecessary runs
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Validate NH_RELEASE_PLZ_TOKEN exists
        run: |
          if [ -z "${{ secrets.NH_RELEASE_PLZ_TOKEN }}" ]; then
            echo "❌ Error: NH_RELEASE_PLZ_TOKEN secret is not configured"
            echo ""
            echo "Release PRs created with GITHUB_TOKEN cannot trigger CI workflows,"
            echo "which causes them to be blocked waiting for 'CI Success' that never runs."
            echo ""
            echo "To fix this:"
            echo "1. Create a fine-grained PAT at: https://github.com/settings/personal-access-tokens/new"
            echo "2. Grant it these permissions for this repository:"
            echo "   - Contents: Read and write"
            echo "   - Pull requests: Read and write"
            echo "   - Workflows: Read and write"
            echo "3. Add it as a repository secret named NH_RELEASE_PLZ_TOKEN at:"
            echo "   https://github.com/nutthead/samoyed/settings/secrets/actions"
            exit 1
          fi
          echo "✅ NH_RELEASE_PLZ_TOKEN is configured"

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.NH_RELEASE_PLZ_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@1780873c7b576612439a134613cc4cc74ce5538c # v1.15.2
        with:
          toolchain: 1.90.0

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-on-failure: true
          prefix-key: "v2-rust"
          key: release-plz

      # Analyzes commits since last release and creates/updates version bump PR
      # Uses conventional commits to determine version bump (major/minor/patch)
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@acb9246af4d59a270d1d4058a8b9af8c3f3a2559 # v0.5.117
        env:
          GITHUB_TOKEN: ${{ secrets.NH_RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: release-pr
