# ============================================================================
# Release PR Workflow
# ============================================================================
# Automated release management with release-plz
# - Monitors master for versionable changes
# - Opens or updates release pull requests
# - Uses rust-cache for faster runs
# - Respects [skip ci] commit hints

name: Release PR

on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

env:
  RUST_VERSION: "1.90.0"
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    # Skip if commit message contains [skip ci] to prevent unnecessary runs
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          # Use PAT if available to trigger CI workflows on release PRs
          # Otherwise fall back to GITHUB_TOKEN (CI won't run but PR will be created)
          token: ${{ secrets.RELEASE_PLZ_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@02be93da58aa71fb456aa9c43b301149248829d8 # v1.15.1
        with:
          toolchain: 1.90.0

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          cache-on-failure: true
          prefix-key: "v2-rust"
          key: release-plz

      # Analyzes commits since last release and creates/updates version bump PR
      # Uses conventional commits to determine version bump (major/minor/patch)
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@acb9246af4d59a270d1d4058a8b9af8c3f3a2559 # v0.5.117
        env:
          # Use PAT if available to trigger CI workflows on release PRs
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN || secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          command: release-pr
